# Test data

GET http://localhost:3123/api HTTP/1.1

###

# Пользователи
## Зарегистрировать пользователя

POST  http://localhost:31337/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "kt1@kt.kt",
  "password": "123123",
  "name": "test_user",
  "avatar": "some.png",
  "type": "pro"
}

###

## Залогинить пользователя

POST http://localhost:31337/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "kt@kt.kt",
  "password": "123123"
}

###

## Проверить, залогинен ли пользователь

GET http://localhost:31337/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt0QGt0Lmt0IiwiaWQiOiI2M2Y1MmIxNWFmYjI1MDVhYmRjNjdmODciLCJpYXQiOjE2NzcwODg4MjIsImV4cCI6MTY3NzI2MTYyMn0.LO6FVbz8aODFlFmaRknCAni1liSBAze_VxslYM_eV5I

###

# Предложения
## Получить список предложений

GET http://localhost:31337/offers HTTP/1.1

###

## Получить информацию о конкретном предложении

GET http://localhost:31337/offers/63f545d47ed839eee03faeee HTTP/1.1

###

## Создать предложение

POST http://localhost:31337/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt0QGt0Lmt0IiwiaWQiOiI2M2Y1MmIxNWFmYjI1MDVhYmRjNjdmODciLCJpYXQiOjE2NzcwODg4MjIsImV4cCI6MTY3NzI2MTYyMn0.LO6FVbz8aODFlFmaRknCAni1liSBAze_VxslYM_eV5I

{
  "title": "Ноыое предожение",
  "description": "Очень интеремносое новое предложенеи",
  "issueDate": "2022-05-12T11:56:37.573Z",
  "city": "Paris",
  "previewImage": "some-pic.png",
  "photos": ["some-pic1.png", "some-pic2.png", "some-pic3.png", "some-pic4.png", "some-pic5.png", "some-pic6.png"],
  "isPremium": false,
  "rating": 3,
  "type": "apartment",
  "roomsCount": 2,
  "guestsCount": 5,
  "price": 1408,
  "features": [],
  "userId": "63f52b15afb2505abdc67f87",
  "commentsCount": 155,
  "coords": [45, 45]
}

###

## Удалить предложение

DELETE http://localhost:31337/offers/63f545d47ed839eee03faeee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt0QGt0Lmt0IiwiaWQiOiI2M2Y1MmIxNWFmYjI1MDVhYmRjNjdmODciLCJpYXQiOjE2NzcwODg4MjIsImV4cCI6MTY3NzI2MTYyMn0.LO6FVbz8aODFlFmaRknCAni1liSBAze_VxslYM_eV5I

###

## Изменить предложение

PATCH http://localhost:31337/offers/63f601cbbcb6c5e169d8d5 HTTP/1.1
Content-Type: application/json

{
  "title": "Обновлено заголовок!",
  "description": "Ух ты!Ух ты!Ух ты!Ух ты!Ух ты!Ух ты!Ух ты!Ух ты!Ух ты!"
}

###

# Комментарии
## Получить список комментариев для преждложения

GET http://localhost:31337/offers/63f601cbbcb6c5e169d8d5e3/comments HTTP/1.1

###

## Создать комментарий для предложения

POST http://localhost:31337/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt0QGt0Lmt0IiwiaWQiOiI2M2Y1MmIxNWFmYjI1MDVhYmRjNjdmODciLCJpYXQiOjE2NzcwODg4MjIsImV4cCI6MTY3NzI2MTYyMn0.LO6FVbz8aODFlFmaRknCAni1liSBAze_VxslYM_eV5I

{
  "text": "321123",
  "userId": "63f52b15afb2505abdc67f87",
  "offerId": "63f601cbbcb6c5e169d8d5e3",
  "rating": 5
}

###

## Создать аватар для пользователя

POST http://localhost:31337/users/63f52b15afb2505abdc67f87/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar" filename="screen.png" 
Content-Type: image/png

< /Users/tmp/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
